workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.trapix.app
    scripts:
      - name: Create .env file
        script: |
          cat > "$CM_BUILD_DIR/.env" << 'ENVEOF'
          apiSecret = h0vWu6MkInNlWHJVfIXmHbIbC66cQvlbSUQI09Whbp
          stripKey = pk_live_51MxTPlESDHY5x8hMMF827y9oRnTiRRtK0R77i6akAfqdPnHeWklHldD3JDscECueAtLw7Wfc0MdGsni7B961W2uq00mSud6XMB
          clientIdPaypal = AV-kpCdSGhgP7Cm-krKtmDsO3S1h4Os7cqd0_z78eEu-thao-XJ5SMY2KuuubLfAzHCEQKkOK6W1ufg4
          secretPaypal = EH5HavBNDK58og9i8OiJH0HkWRLTPxDG-IL5yMHMLWUEbIguZIq45NJ-SlWmngUWN3r6sGmaNrwHZdCh
          modePaypal = sandbox
          ENVEOF
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
