name: tradexpro_flutter
description: A new Flutter project for crypto exchange.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.3.0

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ^3.35.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1  
  
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.5
  flutter_svg: ^2.2.1
  fluttertoast: ^8.2.12
  cached_network_image: ^3.4.1
  http: ^1.5.0
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.0
  webview_flutter_android: ^4.10.1
  pin_code_fields: ^8.0.1
  auto_size_text: ^3.0.0

  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  flutter_switch: ^0.3.2
  modal_bottom_sheet: ^3.0.0
  web_socket_channel: ^3.0.3
  intl_phone_number_input: ^0.7.4
  country_picker: ^2.0.27
  timeline_tile: ^2.0.0
  share_plus: ^11.1.0
  device_info_plus: ^11.5.0
  easy_refresh: ^3.4.0
  crisp_chat: ^2.4.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_stripe: 11.2.0
  stripe_platform_interface: 11.2.0
  stripe_android: 11.2.1
  stripe_ios: 11.2.0
  flutter_dotenv: ^6.0.0
  package_info_plus: ^8.3.1
  http_auth: ^1.0.4
  file: ^7.0.1
  persona_flutter: ^3.2.10
  flutter_widget_from_html: ^0.17.1
  path_provider: ^2.1.5
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  k_chart_plus: ^1.0.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  decimal: ^3.2.4
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^6.0.2
  flutter_countdown_timer: ^4.1.0
  textfield_tags: ^3.0.1
  chat_bubbles: ^1.7.0
  file_picker: ^10.3.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0  # dart run change_app_package_name:main com.new.package.name
  flutter_launcher_icons: ^0.14.4

#dependency_overrides:
#  intl: ^0.19.0

# For information on the generic Dart part of this file, see: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  # For details regarding fonts see: https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  # To Create: dart run flutter_launcher_icons
  image_path: "assets/icons/icLogo.png"
  android: true
  ios: true
  min_sdk_android: 21 # default 21

flutter_native_splash:
  # To Create: dart run flutter_native_splash:create
  # To restore default: dart run flutter_native_splash:remove

  color: "#ffffff"
  # background_image: "assets/dark-background.png"
  # splash image, must be png file and density 4x pixel.
  image: assets/icons/ic_app_icon.png
  # The branding image must be a png file. It is supported for Android, iOS and the Web.
  # branding: assets/images/ic_branding.png


  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/icons/ic_app_icon.png
    # Splash screen background color.
    color: "#ffffff"
    # App icon background color.
    # icon_background_color: "#17202A"
    # The branding property allows you to specify an image used as branding in the splash screen.
    # branding: assets/images/ic_branding.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  image_dark: assets/icons/ic_app_icon.png
  color_dark: "#0F0F0F"
  #icon_background_color_dark: "#17202A"
